services:
  - type: web
    name: snf-news-aggregator
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run server
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: DATABASE_URL
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: DEDUP_AI_ENABLED
        value: true
      - key: DEDUP_TITLE_SIMILARITY_THRESHOLD
        value: 0.7
      - key: DEDUP_DATE_WINDOW_DAYS
        value: 7
      - key: DEDUP_CONTENT_CHARS
        value: 500
      - key: DEDUP_MAX_CANDIDATES
        value: 5

  # Background worker for deficiency tagging
  - type: worker
    name: deficiency-tagger-worker
    env: node
    region: oregon
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && node workers/deficiency-tagger-worker.js
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: DATABASE_URL
        sync: false
