services:
  - type: web
    name: idaho-alf-chatbot
    env: python
    region: oregon
    plan: free
    rootDir: idaho-alf-chatbot/backend
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false